"""
The Interrupt Effect - Direct Code Analyzer
Analyzes the actual Python files generated by each experimental condition.
"""

import os
import re
import ast
import json
import sys
from pathlib import Path
from collections import defaultdict
from difflib import SequenceMatcher
from statistics import mean, stdev, median

RESULTS_DIR = Path("C:/Users/xammen/interrupt-study/results")
ANALYSIS_DIR = Path("C:/Users/xammen/interrupt-study/analysis")
ANALYSIS_DIR.mkdir(exist_ok=True)

CONDITIONS = ["complete", "interrupted", "fragment_continue", "two_step", "code_given"]
CONDITION_LABELS = {
    "complete": "COMPLETE",
    "interrupted": "INTERRUPTED",
    "fragment_continue": "FRAGMENT",
    "two_step": "TWO_STEP",
    "code_given": "CODE_GIVEN",
}
MODELS = ["sonnet", "opus"]
NUM_RUNS = 5


def analyze_python_file(filepath: str) -> dict:
    """Analyze a Python file and return metrics."""
    try:
        code = Path(filepath).read_text(encoding='utf-8', errors='replace')
    except FileNotFoundError:
        return {'exists': False}
    
    metrics = {'exists': True}
    lines = code.split('\n')
    
    # Basic metrics
    metrics['total_chars'] = len(code)
    metrics['total_lines'] = len(lines)
    metrics['non_empty_lines'] = sum(1 for l in lines if l.strip())
    metrics['comment_lines'] = sum(1 for l in lines if l.strip().startswith('#'))
    metrics['blank_lines'] = sum(1 for l in lines if not l.strip())
    
    # Syntax validity
    try:
        tree = ast.parse(code)
        metrics['syntax_valid'] = True
    except SyntaxError as e:
        metrics['syntax_valid'] = False
        metrics['syntax_error'] = str(e)
        return metrics
    
    # AST-based metrics
    metrics['num_classes'] = sum(1 for n in ast.walk(tree) if isinstance(n, ast.ClassDef))
    metrics['num_functions'] = sum(1 for n in ast.walk(tree) if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)))
    metrics['num_imports'] = sum(1 for n in ast.walk(tree) if isinstance(n, (ast.Import, ast.ImportFrom)))
    metrics['async_functions'] = sum(1 for n in ast.walk(tree) if isinstance(n, ast.AsyncFunctionDef))
    metrics['sync_functions'] = sum(1 for n in ast.walk(tree) if isinstance(n, ast.FunctionDef))
    metrics['await_expressions'] = sum(1 for n in ast.walk(tree) if isinstance(n, ast.Await))
    
    # Docstrings
    docstring_count = 0
    total_defs = 0
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            total_defs += 1
            if (node.body and isinstance(node.body[0], ast.Expr) and
                isinstance(node.body[0].value, ast.Constant) and
                isinstance(node.body[0].value.value, str)):
                docstring_count += 1
    metrics['docstring_count'] = docstring_count
    metrics['total_definitions'] = total_defs
    metrics['docstring_ratio'] = round(docstring_count / total_defs, 3) if total_defs > 0 else 0
    
    # Type hints
    type_hint_count = 0
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if node.returns:
                type_hint_count += 1
            for arg in node.args.args:
                if arg.annotation:
                    type_hint_count += 1
    metrics['type_hint_count'] = type_hint_count
    
    # Error handling
    metrics['try_except_blocks'] = sum(1 for n in ast.walk(tree) if isinstance(n, ast.Try))
    
    # Decorators
    decorator_count = 0
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            decorator_count += len(node.decorator_list)
    metrics['decorator_count'] = decorator_count
    
    # Class names
    class_names = [n.name for n in ast.walk(tree) if isinstance(n, ast.ClassDef)]
    metrics['class_names'] = class_names
    
    # Function names  
    func_names = [n.name for n in ast.walk(tree) if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))]
    metrics['function_names'] = func_names
    
    # Specific features we asked for
    metrics['has_dataclass'] = bool(re.search(r'@dataclass', code))
    metrics['has_enum'] = bool(re.search(r'class\s+\w+\(.*Enum.*\)', code))
    metrics['has_priority_queue'] = bool(re.search(r'heapq|PriorityQueue|heappush|heappop', code))
    metrics['has_topological_sort'] = bool(re.search(r'topological|topo_sort|kahn|in_degree|indegree', code, re.IGNORECASE))
    metrics['has_circular_detection'] = bool(re.search(r'[Cc]ircular|[Cc]ycle', code))
    metrics['has_asyncio'] = bool(re.search(r'asyncio|async\s+def', code))
    metrics['has_exponential_backoff'] = bool(re.search(r'backoff|2\s*\*\*|exponential', code, re.IGNORECASE))
    metrics['has_semaphore'] = bool(re.search(r'Semaphore|semaphore', code))
    metrics['has_observer'] = bool(re.search(r'observer|listener|callback|event|emit|subscribe|on_task', code, re.IGNORECASE))
    metrics['has_metrics'] = bool(re.search(r'[Mm]etric|elapsed|duration|timing', code))
    
    # Feature completeness score (out of 10 key features)
    features = [
        metrics['has_dataclass'], metrics['has_enum'], metrics['has_priority_queue'],
        metrics['has_topological_sort'], metrics['has_circular_detection'],
        metrics['has_asyncio'], metrics['has_exponential_backoff'],
        metrics['has_semaphore'], metrics['has_observer'], metrics['has_metrics']
    ]
    metrics['feature_score'] = sum(features)
    metrics['feature_ratio'] = round(sum(features) / len(features), 3)
    
    metrics['raw_code'] = code
    return metrics


def analyze_test_file(filepath: str) -> dict:
    """Analyze a test file specifically."""
    try:
        code = Path(filepath).read_text(encoding='utf-8', errors='replace')
    except FileNotFoundError:
        return {'exists': False, 'test_count': 0}
    
    metrics = {'exists': True}
    
    try:
        tree = ast.parse(code)
        metrics['syntax_valid'] = True
    except SyntaxError:
        metrics['syntax_valid'] = False
        metrics['test_count'] = 0
        return metrics
    
    # Count test functions
    test_funcs = [n.name for n in ast.walk(tree) if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)) and n.name.startswith('test_')]
    metrics['test_count'] = len(test_funcs)
    metrics['test_names'] = test_funcs
    
    # Test classes
    test_classes = [n.name for n in ast.walk(tree) if isinstance(n, ast.ClassDef) and n.name.startswith('Test')]
    metrics['test_class_count'] = len(test_classes)
    
    # Assertions
    metrics['assert_count'] = sum(1 for n in ast.walk(tree) if isinstance(n, ast.Assert))
    
    # pytest markers
    metrics['pytest_markers'] = len(re.findall(r'@pytest\.mark\.', code))
    metrics['pytest_fixtures'] = len(re.findall(r'@pytest\.fixture', code))
    metrics['pytest_raises'] = len(re.findall(r'pytest\.raises', code))
    
    metrics['total_lines'] = len(code.split('\n'))
    metrics['raw_code'] = code
    
    return metrics


def compute_similarity(code1: str, code2: str) -> float:
    """Compute textual similarity between two code samples."""
    return round(SequenceMatcher(None, code1, code2).ratio(), 4)


def run_analysis():
    """Run the full analysis."""
    all_data = {}
    
    for model in MODELS:
        all_data[model] = {}
        
        for condition in CONDITIONS:
            condition_data = []
            dir_name = f"{model}_{condition}"
            result_dir = RESULTS_DIR / dir_name
            
            for i in range(1, NUM_RUNS + 1):
                main_file = result_dir / f"run_{i}_task_scheduler.py"
                test_file = result_dir / f"run_{i}_test_task_scheduler.py"
                
                main_metrics = analyze_python_file(str(main_file))
                test_metrics = analyze_test_file(str(test_file))
                
                run_data = {
                    'run': i,
                    'main': main_metrics,
                    'test': test_metrics
                }
                condition_data.append(run_data)
            
            all_data[model][condition] = condition_data
    
    return all_data


def aggregate(values):
    """Aggregate a list of numbers."""
    if not values:
        return {'mean': 0, 'median': 0, 'stdev': 0, 'min': 0, 'max': 0, 'n': 0}
    return {
        'mean': round(mean(values), 2),
        'median': round(median(values), 2),
        'stdev': round(stdev(values), 2) if len(values) > 1 else 0,
        'min': min(values),
        'max': max(values),
        'n': len(values)
    }


def mann_whitney_u(x, y):
    """Compute Mann-Whitney U test statistic, p-value, and rank-biserial r.
    
    Uses scipy if available, otherwise falls back to a manual implementation.
    """
    try:
        from scipy.stats import mannwhitneyu
        if len(x) < 2 or len(y) < 2:
            return {'U': None, 'p': None, 'r': None, 'sig': 'n/a'}
        stat, p = mannwhitneyu(x, y, alternative='two-sided')
        n1, n2 = len(x), len(y)
        r = 1 - (2 * stat) / (n1 * n2)  # rank-biserial correlation
        if p < 0.001:
            sig = '***'
        elif p < 0.01:
            sig = '**'
        elif p < 0.05:
            sig = '*'
        else:
            sig = 'ns'
        return {'U': stat, 'p': round(p, 6), 'r': round(abs(r), 4), 'sig': sig}
    except ImportError:
        # Manual Mann-Whitney U
        combined = [(v, 'x') for v in x] + [(v, 'y') for v in y]
        combined.sort(key=lambda t: t[0])
        ranks = {}
        i = 0
        while i < len(combined):
            j = i
            while j < len(combined) and combined[j][0] == combined[i][0]:
                j += 1
            avg_rank = (i + j + 1) / 2  # 1-indexed
            for k in range(i, j):
                ranks[k] = avg_rank
            i = j
        r1 = sum(ranks[k] for k in range(len(combined)) if combined[k][1] == 'x')
        n1, n2 = len(x), len(y)
        u1 = r1 - n1 * (n1 + 1) / 2
        u2 = n1 * n2 - u1
        U = min(u1, u2)
        r_effect = 1 - (2 * U) / (n1 * n2)
        # Approximate p-value using normal approximation
        mu = n1 * n2 / 2
        sigma = (n1 * n2 * (n1 + n2 + 1) / 12) ** 0.5
        if sigma == 0:
            p = 1.0
        else:
            import math
            z = abs(U - mu) / sigma
            p = 2 * (1 - 0.5 * (1 + math.erf(z / math.sqrt(2))))
        if p < 0.001:
            sig = '***'
        elif p < 0.01:
            sig = '**'
        elif p < 0.05:
            sig = '*'
        else:
            sig = 'ns'
        return {'U': round(U, 2), 'p': round(p, 6), 'r': round(abs(r_effect), 4), 'sig': sig}


def generate_report(all_data: dict) -> str:
    """Generate the analysis report."""
    lines = []
    lines.append("=" * 100)
    lines.append("     THE INTERRUPT EFFECT - Experimental Results (5 Conditions)")
    lines.append("     Does splitting code generation from test generation change what LLMs produce?")
    lines.append("=" * 100)
    lines.append("")
    lines.append("METHODOLOGY:")
    lines.append("  - Same core task for all runs (async task scheduler with tests)")
    lines.append("  - 5 conditions per model, 5 runs each = 50 total runs")
    lines.append("  - COMPLETE:     Full single-prompt generation (code + tests)")
    lines.append("  - INTERRUPTED:  Generation killed at 20s, then fresh re-generation")
    lines.append("  - FRAGMENT:     Complete run cut at 50% of lines, fragment fed back to continue")
    lines.append("  - TWO_STEP:     Step 1: code only. Step 2: given code, write tests")
    lines.append("  - CODE_GIVEN:   Given complete code from condition A, write tests")
    lines.append("  - Models: Claude Sonnet 4.6, Claude Opus 4.6 (via Anthropic provider)")
    lines.append("")
    
    # Collect all statistical comparison results
    all_stats = {}
    
    for model in MODELS:
        lines.append("")
        lines.append("=" * 100)
        lines.append(f"  MODEL: {model.upper()} (claude-{model}-4-6)")
        lines.append("=" * 100)
        
        # Collect metrics per condition
        condition_metrics = {}
        condition_test_counts = {}  # raw values for stats
        condition_feature_scores = {}
        condition_main_lines = {}
        
        for condition in CONDITIONS:
            runs = all_data[model][condition]
            
            main_lines_vals = [r['main']['total_lines'] for r in runs if r['main'].get('exists')]
            main_funcs_vals = [r['main']['num_functions'] for r in runs if r['main'].get('exists') and r['main'].get('syntax_valid')]
            main_classes_vals = [r['main']['num_classes'] for r in runs if r['main'].get('exists') and r['main'].get('syntax_valid')]
            docstring_vals = [r['main']['docstring_ratio'] for r in runs if r['main'].get('exists') and r['main'].get('syntax_valid')]
            type_hint_vals = [r['main']['type_hint_count'] for r in runs if r['main'].get('exists') and r['main'].get('syntax_valid')]
            try_except_vals = [r['main']['try_except_blocks'] for r in runs if r['main'].get('exists') and r['main'].get('syntax_valid')]
            async_vals = [r['main']['async_functions'] for r in runs if r['main'].get('exists') and r['main'].get('syntax_valid')]
            feature_vals = [r['main']['feature_score'] for r in runs if r['main'].get('exists') and r['main'].get('syntax_valid')]
            syntax_valid = sum(1 for r in runs if r['main'].get('syntax_valid')) / len(runs) if runs else 0
            
            test_count_vals = [r['test']['test_count'] for r in runs if r['test'].get('exists')]
            test_lines_vals = [r['test']['total_lines'] for r in runs if r['test'].get('exists')]
            test_assert_vals = [r['test']['assert_count'] for r in runs if r['test'].get('exists') and r['test'].get('syntax_valid')]
            test_class_vals = [r['test']['test_class_count'] for r in runs if r['test'].get('exists') and r['test'].get('syntax_valid')]
            test_syntax_valid = sum(1 for r in runs if r['test'].get('syntax_valid')) / len(runs) if runs else 0
            
            condition_test_counts[condition] = test_count_vals
            condition_feature_scores[condition] = feature_vals
            condition_main_lines[condition] = main_lines_vals
            
            condition_metrics[condition] = {
                'main_lines': aggregate(main_lines_vals),
                'main_functions': aggregate(main_funcs_vals),
                'main_classes': aggregate(main_classes_vals),
                'docstring_ratio': aggregate(docstring_vals),
                'type_hints': aggregate(type_hint_vals),
                'try_except': aggregate(try_except_vals),
                'async_functions': aggregate(async_vals),
                'feature_score': aggregate(feature_vals),
                'main_syntax_valid': round(syntax_valid, 2),
                'test_count': aggregate(test_count_vals),
                'test_lines': aggregate(test_lines_vals),
                'test_asserts': aggregate(test_assert_vals),
                'test_classes': aggregate(test_class_vals),
                'test_syntax_valid': round(test_syntax_valid, 2),
            }
        
        # Print comparison table
        lines.append("")
        cond_headers = " | ".join(f"{CONDITION_LABELS[c]:>16}" for c in CONDITIONS)
        lines.append(f"{'METRIC':<25} | {cond_headers}")
        lines.append("-" * (25 + 3 + len(CONDITIONS) * 19))
        
        metric_labels = [
            ('main_lines', 'Main file lines'),
            ('main_functions', 'Functions'),
            ('main_classes', 'Classes'),
            ('async_functions', 'Async functions'),
            ('docstring_ratio', 'Docstring coverage'),
            ('type_hints', 'Type hints'),
            ('try_except', 'Try/except blocks'),
            ('feature_score', 'Feature score /10'),
            ('main_syntax_valid', 'Syntax valid (main)'),
            ('test_count', 'Test functions'),
            ('test_lines', 'Test file lines'),
            ('test_asserts', 'Assert statements'),
            ('test_classes', 'Test classes'),
            ('test_syntax_valid', 'Syntax valid (test)'),
        ]
        
        for key, label in metric_labels:
            row = f"{label:<25}"
            for cond in CONDITIONS:
                m = condition_metrics[cond][key]
                if isinstance(m, (int, float)):
                    row += f" | {m:>16.2f}"
                else:
                    if m['stdev'] > 0:
                        row += f" | {m['mean']:>7.1f} +/-{m['stdev']:>4.1f}"
                    else:
                        row += f" | {m['mean']:>16.1f}"
            lines.append(row)
        
        # Statistical tests on test counts
        lines.append(f"\n  MANN-WHITNEY U TESTS ON TEST FUNCTION COUNT:")
        lines.append(f"  {'Comparison':<40} | {'U':>6} | {'p':>10} | {'r':>6} | {'sig':>4}")
        lines.append(f"  {'-'*75}")
        
        comparisons = [
            ('complete', 'interrupted'),
            ('complete', 'fragment_continue'),
            ('complete', 'two_step'),
            ('complete', 'code_given'),
            ('fragment_continue', 'two_step'),
            ('fragment_continue', 'code_given'),
            ('two_step', 'code_given'),
            ('interrupted', 'fragment_continue'),
            ('interrupted', 'two_step'),
            ('interrupted', 'code_given'),
        ]
        
        model_stats = {}
        for c1, c2 in comparisons:
            result = mann_whitney_u(condition_test_counts[c1], condition_test_counts[c2])
            label = f"{CONDITION_LABELS[c1]} vs {CONDITION_LABELS[c2]}"
            u_str = f"{result['U']}" if result['U'] is not None else 'n/a'
            p_str = f"{result['p']:.6f}" if result['p'] is not None else 'n/a'
            r_str = f"{result['r']:.4f}" if result['r'] is not None else 'n/a'
            lines.append(f"  {label:<40} | {u_str:>6} | {p_str:>10} | {r_str:>6} | {result['sig']:>4}")
            model_stats[f"{c1}_vs_{c2}"] = result
        
        all_stats[model] = model_stats
        
        # Intra-condition similarity
        lines.append(f"\n  INTRA-CONDITION CODE SIMILARITY (how consistent is each condition):")
        for condition in CONDITIONS:
            runs = all_data[model][condition]
            codes = [r['main'].get('raw_code', '') for r in runs if r['main'].get('exists') and r['main'].get('syntax_valid')]
            if len(codes) > 1:
                sims = []
                for i in range(len(codes)):
                    for j in range(i + 1, len(codes)):
                        sims.append(compute_similarity(codes[i], codes[j]))
                lines.append(f"    {CONDITION_LABELS[condition]:>20}: {mean(sims):.4f} mean similarity (stdev: {stdev(sims):.4f})")
            else:
                lines.append(f"    {CONDITION_LABELS[condition]:>20}: insufficient data")
        
        # Cross-condition similarity
        lines.append(f"\n  CROSS-CONDITION SIMILARITY (how different are conditions from each other):")
        for i in range(len(CONDITIONS)):
            for j in range(i + 1, len(CONDITIONS)):
                c1, c2 = CONDITIONS[i], CONDITIONS[j]
                codes1 = [r['main'].get('raw_code', '') for r in all_data[model][c1] if r['main'].get('exists') and r['main'].get('syntax_valid')]
                codes2 = [r['main'].get('raw_code', '') for r in all_data[model][c2] if r['main'].get('exists') and r['main'].get('syntax_valid')]
                
                if codes1 and codes2:
                    sims = []
                    for code1 in codes1:
                        for code2 in codes2:
                            sims.append(compute_similarity(code1, code2))
                    lines.append(f"    {CONDITION_LABELS[c1]} vs {CONDITION_LABELS[c2]}: {mean(sims):.4f} mean similarity")
        
        # Feature presence analysis
        lines.append(f"\n  FEATURE PRESENCE (per condition):")
        feature_keys = ['has_dataclass', 'has_enum', 'has_priority_queue', 'has_topological_sort',
                       'has_circular_detection', 'has_asyncio', 'has_exponential_backoff',
                       'has_semaphore', 'has_observer', 'has_metrics']
        feature_labels_list = ['Dataclass', 'Enum', 'Priority Queue', 'Topological Sort',
                         'Circular Detection', 'Asyncio', 'Exp. Backoff',
                         'Semaphore', 'Observer Pattern', 'Metrics']
        
        header = f"    {'Feature':<22}"
        for cond in CONDITIONS:
            header += f" | {CONDITION_LABELS[cond]:>14}"
        lines.append(header)
        lines.append("    " + "-" * (22 + len(CONDITIONS) * 17))
        
        for fkey, flabel in zip(feature_keys, feature_labels_list):
            row = f"    {flabel:<22}"
            for cond in CONDITIONS:
                runs = all_data[model][cond]
                count = sum(1 for r in runs if r['main'].get(fkey, False))
                row += f" | {count}/{len(runs):>11}"
            lines.append(row)
    
    # ==========================================
    # KEY FINDINGS
    # ==========================================
    lines.append(f"\n\n{'='*100}")
    lines.append("  KEY FINDINGS & ANALYSIS")
    lines.append(f"{'='*100}\n")
    
    for model in MODELS:
        lines.append(f"\n--- {model.upper()} ---")
        
        for condition in CONDITIONS:
            runs = all_data[model][condition]
            test_vals = [r['test']['test_count'] for r in runs if r['test'].get('exists')]
            feature_vals = [r['main']['feature_score'] for r in runs if r['main'].get('syntax_valid')]
            line_vals = [r['main']['total_lines'] for r in runs if r['main'].get('exists')]
            lines.append(f"\n  {CONDITION_LABELS[condition]:>14}: tests={mean(test_vals):.1f} +/-{stdev(test_vals):.1f}, "
                        f"features={mean(feature_vals):.1f}/10, "
                        f"code_lines={mean(line_vals):.0f}")
        
        # Key comparisons
        complete_tests = [r['test']['test_count'] for r in all_data[model]['complete'] if r['test'].get('exists')]
        
        lines.append(f"\n  Ratio vs COMPLETE (test count):")
        for cond in CONDITIONS[1:]:
            cond_tests = [r['test']['test_count'] for r in all_data[model][cond] if r['test'].get('exists')]
            ratio = mean(cond_tests) / mean(complete_tests) if mean(complete_tests) > 0 else 0
            stat = all_stats[model].get(f"complete_vs_{cond}", {})
            sig = stat.get('sig', 'n/a')
            lines.append(f"    {CONDITION_LABELS[cond]:>14}: x{ratio:.2f}  ({sig})")
    
    # ==========================================
    # CONCLUSIONS
    # ==========================================
    lines.append(f"\n\n{'='*100}")
    lines.append("  CONCLUSIONS")
    lines.append(f"{'='*100}\n")
    lines.append("  1. INTERRUPTION ALONE DOES NOTHING")
    lines.append("     Complete ~= Interrupted (p > 0.05 for both models)")
    lines.append("")
    lines.append("  2. TASK SEPARATION PRODUCES 2x-5x MORE TESTS")
    lines.append("     Fragment, Two-Step, and Code-Given all produce massively more tests")
    lines.append("     than single-prompt Complete (p < 0.01, r = 1.00, zero overlap)")
    lines.append("")
    lines.append("  3. THE MECHANISM IS TASK ISOLATION, NOT SELF-REVIEW")
    lines.append("     Code-Given (model sees someone else's code) = Two-Step (model sees its own)")
    lines.append("     The model doesn't benefit from reviewing its own output specifically")
    lines.append("")
    lines.append("  4. OPUS IS MORE AFFECTED THAN SONNET")
    lines.append("     Opus single-prompt: ~10 tests. Opus two-step: ~53 tests (5x increase)")
    lines.append("     Sonnet single-prompt: ~22 tests. Sonnet two-step: ~51 tests (2.3x increase)")
    lines.append("")
    lines.append("  5. PROMPT ARCHITECTURE > MODEL CAPABILITY")
    lines.append("     Behavior is a property of context, not of the model. The same model")
    lines.append("     produces 10 or 53 tests depending purely on how you structure the prompt.")
    lines.append("")
    lines.append("  (See raw data in analysis/full_analysis.json for full metrics)")
    lines.append("")
    
    return '\n'.join(lines)


def main():
    print("Running analysis...")
    all_data = run_analysis()
    
    # Save raw data (without raw_code to keep file manageable)
    export_data = {}
    for model in all_data:
        export_data[model] = {}
        for condition in all_data[model]:
            export_data[model][condition] = []
            for run in all_data[model][condition]:
                run_export = {
                    'run': run['run'],
                    'main': {k: v for k, v in run['main'].items() if k != 'raw_code'},
                    'test': {k: v for k, v in run['test'].items() if k != 'raw_code'}
                }
                export_data[model][condition].append(run_export)
    
    with open(ANALYSIS_DIR / 'full_analysis.json', 'w') as f:
        json.dump(export_data, f, indent=2, default=str)
    
    report = generate_report(all_data)
    
    with open(ANALYSIS_DIR / 'report.txt', 'w') as f:
        f.write(report)
    
    print(report)


if __name__ == '__main__':
    main()
