"""
The Interrupt Effect - Direct Code Analyzer
Analyzes the actual Python files generated by each experimental condition.
"""

import os
import re
import ast
import json
import sys
from pathlib import Path
from collections import defaultdict
from difflib import SequenceMatcher
from statistics import mean, stdev, median

RESULTS_DIR = Path("C:/Users/xammen/interrupt-study/results")
ANALYSIS_DIR = Path("C:/Users/xammen/interrupt-study/analysis")
ANALYSIS_DIR.mkdir(exist_ok=True)

CONDITIONS = ["complete", "interrupted", "fragment_continue"]
MODELS = ["sonnet", "opus"]
NUM_RUNS = 5


def analyze_python_file(filepath: str) -> dict:
    """Analyze a Python file and return metrics."""
    try:
        code = Path(filepath).read_text(encoding='utf-8', errors='replace')
    except FileNotFoundError:
        return {'exists': False}
    
    metrics = {'exists': True}
    lines = code.split('\n')
    
    # Basic metrics
    metrics['total_chars'] = len(code)
    metrics['total_lines'] = len(lines)
    metrics['non_empty_lines'] = sum(1 for l in lines if l.strip())
    metrics['comment_lines'] = sum(1 for l in lines if l.strip().startswith('#'))
    metrics['blank_lines'] = sum(1 for l in lines if not l.strip())
    
    # Syntax validity
    try:
        tree = ast.parse(code)
        metrics['syntax_valid'] = True
    except SyntaxError as e:
        metrics['syntax_valid'] = False
        metrics['syntax_error'] = str(e)
        return metrics
    
    # AST-based metrics
    metrics['num_classes'] = sum(1 for n in ast.walk(tree) if isinstance(n, ast.ClassDef))
    metrics['num_functions'] = sum(1 for n in ast.walk(tree) if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)))
    metrics['num_imports'] = sum(1 for n in ast.walk(tree) if isinstance(n, (ast.Import, ast.ImportFrom)))
    metrics['async_functions'] = sum(1 for n in ast.walk(tree) if isinstance(n, ast.AsyncFunctionDef))
    metrics['sync_functions'] = sum(1 for n in ast.walk(tree) if isinstance(n, ast.FunctionDef))
    metrics['await_expressions'] = sum(1 for n in ast.walk(tree) if isinstance(n, ast.Await))
    
    # Docstrings
    docstring_count = 0
    total_defs = 0
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            total_defs += 1
            if (node.body and isinstance(node.body[0], ast.Expr) and
                isinstance(node.body[0].value, ast.Constant) and
                isinstance(node.body[0].value.value, str)):
                docstring_count += 1
    metrics['docstring_count'] = docstring_count
    metrics['total_definitions'] = total_defs
    metrics['docstring_ratio'] = round(docstring_count / total_defs, 3) if total_defs > 0 else 0
    
    # Type hints
    type_hint_count = 0
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if node.returns:
                type_hint_count += 1
            for arg in node.args.args:
                if arg.annotation:
                    type_hint_count += 1
    metrics['type_hint_count'] = type_hint_count
    
    # Error handling
    metrics['try_except_blocks'] = sum(1 for n in ast.walk(tree) if isinstance(n, ast.Try))
    
    # Decorators
    decorator_count = 0
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            decorator_count += len(node.decorator_list)
    metrics['decorator_count'] = decorator_count
    
    # Class names
    class_names = [n.name for n in ast.walk(tree) if isinstance(n, ast.ClassDef)]
    metrics['class_names'] = class_names
    
    # Function names  
    func_names = [n.name for n in ast.walk(tree) if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))]
    metrics['function_names'] = func_names
    
    # Specific features we asked for
    metrics['has_dataclass'] = bool(re.search(r'@dataclass', code))
    metrics['has_enum'] = bool(re.search(r'class\s+\w+\(.*Enum.*\)', code))
    metrics['has_priority_queue'] = bool(re.search(r'heapq|PriorityQueue|heappush|heappop', code))
    metrics['has_topological_sort'] = bool(re.search(r'topological|topo_sort|kahn|in_degree|indegree', code, re.IGNORECASE))
    metrics['has_circular_detection'] = bool(re.search(r'[Cc]ircular|[Cc]ycle', code))
    metrics['has_asyncio'] = bool(re.search(r'asyncio|async\s+def', code))
    metrics['has_exponential_backoff'] = bool(re.search(r'backoff|2\s*\*\*|exponential', code, re.IGNORECASE))
    metrics['has_semaphore'] = bool(re.search(r'Semaphore|semaphore', code))
    metrics['has_observer'] = bool(re.search(r'observer|listener|callback|event|emit|subscribe|on_task', code, re.IGNORECASE))
    metrics['has_metrics'] = bool(re.search(r'[Mm]etric|elapsed|duration|timing', code))
    
    # Feature completeness score (out of 10 key features)
    features = [
        metrics['has_dataclass'], metrics['has_enum'], metrics['has_priority_queue'],
        metrics['has_topological_sort'], metrics['has_circular_detection'],
        metrics['has_asyncio'], metrics['has_exponential_backoff'],
        metrics['has_semaphore'], metrics['has_observer'], metrics['has_metrics']
    ]
    metrics['feature_score'] = sum(features)
    metrics['feature_ratio'] = round(sum(features) / len(features), 3)
    
    metrics['raw_code'] = code
    return metrics


def analyze_test_file(filepath: str) -> dict:
    """Analyze a test file specifically."""
    try:
        code = Path(filepath).read_text(encoding='utf-8', errors='replace')
    except FileNotFoundError:
        return {'exists': False, 'test_count': 0}
    
    metrics = {'exists': True}
    
    try:
        tree = ast.parse(code)
        metrics['syntax_valid'] = True
    except SyntaxError:
        metrics['syntax_valid'] = False
        metrics['test_count'] = 0
        return metrics
    
    # Count test functions
    test_funcs = [n.name for n in ast.walk(tree) if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)) and n.name.startswith('test_')]
    metrics['test_count'] = len(test_funcs)
    metrics['test_names'] = test_funcs
    
    # Test classes
    test_classes = [n.name for n in ast.walk(tree) if isinstance(n, ast.ClassDef) and n.name.startswith('Test')]
    metrics['test_class_count'] = len(test_classes)
    
    # Assertions
    metrics['assert_count'] = sum(1 for n in ast.walk(tree) if isinstance(n, ast.Assert))
    
    # pytest markers
    metrics['pytest_markers'] = len(re.findall(r'@pytest\.mark\.', code))
    metrics['pytest_fixtures'] = len(re.findall(r'@pytest\.fixture', code))
    metrics['pytest_raises'] = len(re.findall(r'pytest\.raises', code))
    
    metrics['total_lines'] = len(code.split('\n'))
    metrics['raw_code'] = code
    
    return metrics


def compute_similarity(code1: str, code2: str) -> float:
    """Compute textual similarity between two code samples."""
    return round(SequenceMatcher(None, code1, code2).ratio(), 4)


def run_analysis():
    """Run the full analysis."""
    all_data = {}
    
    for model in MODELS:
        all_data[model] = {}
        
        for condition in CONDITIONS:
            condition_data = []
            dir_name = f"{model}_{condition}"
            result_dir = RESULTS_DIR / dir_name
            
            for i in range(1, NUM_RUNS + 1):
                main_file = result_dir / f"run_{i}_task_scheduler.py"
                test_file = result_dir / f"run_{i}_test_task_scheduler.py"
                
                main_metrics = analyze_python_file(str(main_file))
                test_metrics = analyze_test_file(str(test_file))
                
                run_data = {
                    'run': i,
                    'main': main_metrics,
                    'test': test_metrics
                }
                condition_data.append(run_data)
            
            all_data[model][condition] = condition_data
    
    return all_data


def aggregate(values):
    """Aggregate a list of numbers."""
    if not values:
        return {'mean': 0, 'median': 0, 'stdev': 0, 'min': 0, 'max': 0, 'n': 0}
    return {
        'mean': round(mean(values), 2),
        'median': round(median(values), 2),
        'stdev': round(stdev(values), 2) if len(values) > 1 else 0,
        'min': min(values),
        'max': max(values),
        'n': len(values)
    }


def generate_report(all_data: dict) -> str:
    """Generate the analysis report."""
    lines = []
    lines.append("=" * 80)
    lines.append("     THE INTERRUPT EFFECT - Experimental Results")
    lines.append("     Does interrupting LLM code generation change the output?")
    lines.append("=" * 80)
    lines.append("")
    lines.append("METHODOLOGY:")
    lines.append("  - Same prompt used for all runs (async task scheduler with tests)")
    lines.append("  - 3 conditions per model, 5 runs each = 30 total runs")
    lines.append("  - COMPLETE:    Full uninterrupted generation")
    lines.append("  - INTERRUPTED: Generation killed at 20s, then fresh re-generation")
    lines.append("  - FRAGMENT:    Complete run cut at 50%, fragment fed back to continue")
    lines.append("  - Models: Claude Sonnet 4.6, Claude Opus 4.6 (via Anthropic API)")
    lines.append("")
    
    for model in MODELS:
        lines.append("")
        lines.append("=" * 80)
        lines.append(f"  MODEL: {model.upper()} (claude-{model}-4-6)")
        lines.append("=" * 80)
        
        # Collect metrics per condition
        condition_metrics = {}
        
        for condition in CONDITIONS:
            runs = all_data[model][condition]
            
            main_lines_vals = [r['main']['total_lines'] for r in runs if r['main'].get('exists')]
            main_funcs_vals = [r['main']['num_functions'] for r in runs if r['main'].get('exists') and r['main'].get('syntax_valid')]
            main_classes_vals = [r['main']['num_classes'] for r in runs if r['main'].get('exists') and r['main'].get('syntax_valid')]
            docstring_vals = [r['main']['docstring_ratio'] for r in runs if r['main'].get('exists') and r['main'].get('syntax_valid')]
            type_hint_vals = [r['main']['type_hint_count'] for r in runs if r['main'].get('exists') and r['main'].get('syntax_valid')]
            try_except_vals = [r['main']['try_except_blocks'] for r in runs if r['main'].get('exists') and r['main'].get('syntax_valid')]
            async_vals = [r['main']['async_functions'] for r in runs if r['main'].get('exists') and r['main'].get('syntax_valid')]
            feature_vals = [r['main']['feature_score'] for r in runs if r['main'].get('exists') and r['main'].get('syntax_valid')]
            syntax_valid = sum(1 for r in runs if r['main'].get('syntax_valid')) / len(runs) if runs else 0
            
            test_count_vals = [r['test']['test_count'] for r in runs if r['test'].get('exists')]
            test_lines_vals = [r['test']['total_lines'] for r in runs if r['test'].get('exists')]
            test_assert_vals = [r['test']['assert_count'] for r in runs if r['test'].get('exists') and r['test'].get('syntax_valid')]
            test_syntax_valid = sum(1 for r in runs if r['test'].get('syntax_valid')) / len(runs) if runs else 0
            
            condition_metrics[condition] = {
                'main_lines': aggregate(main_lines_vals),
                'main_functions': aggregate(main_funcs_vals),
                'main_classes': aggregate(main_classes_vals),
                'docstring_ratio': aggregate(docstring_vals),
                'type_hints': aggregate(type_hint_vals),
                'try_except': aggregate(try_except_vals),
                'async_functions': aggregate(async_vals),
                'feature_score': aggregate(feature_vals),
                'main_syntax_valid': round(syntax_valid, 2),
                'test_count': aggregate(test_count_vals),
                'test_lines': aggregate(test_lines_vals),
                'test_asserts': aggregate(test_assert_vals),
                'test_syntax_valid': round(test_syntax_valid, 2),
            }
        
        # Print comparison table
        lines.append("")
        lines.append(f"{'METRIC':<25} | {'COMPLETE':>18} | {'INTERRUPTED':>18} | {'FRAGMENT':>18}")
        lines.append("-" * 86)
        
        metric_labels = [
            ('main_lines', 'Main file lines'),
            ('main_functions', 'Functions'),
            ('main_classes', 'Classes'),
            ('async_functions', 'Async functions'),
            ('docstring_ratio', 'Docstring coverage'),
            ('type_hints', 'Type hints'),
            ('try_except', 'Try/except blocks'),
            ('feature_score', 'Feature score /10'),
            ('main_syntax_valid', 'Syntax valid (main)'),
            ('test_count', 'Test functions'),
            ('test_lines', 'Test file lines'),
            ('test_asserts', 'Assert statements'),
            ('test_syntax_valid', 'Syntax valid (test)'),
        ]
        
        for key, label in metric_labels:
            row = f"{label:<25}"
            for cond in CONDITIONS:
                m = condition_metrics[cond][key]
                if isinstance(m, (int, float)):
                    row += f" | {m:>18.2f}"
                else:
                    if m['stdev'] > 0:
                        row += f" | {m['mean']:>8.1f} +/-{m['stdev']:>5.1f}"
                    else:
                        row += f" | {m['mean']:>18.1f}"
            lines.append(row)
        
        # Intra-condition similarity (how different are runs within the same condition)
        lines.append(f"\n  INTRA-CONDITION CODE SIMILARITY (how consistent is each condition):")
        for condition in CONDITIONS:
            runs = all_data[model][condition]
            codes = [r['main'].get('raw_code', '') for r in runs if r['main'].get('exists') and r['main'].get('syntax_valid')]
            if len(codes) > 1:
                sims = []
                for i in range(len(codes)):
                    for j in range(i + 1, len(codes)):
                        sims.append(compute_similarity(codes[i], codes[j]))
                lines.append(f"    {condition:>20}: {mean(sims):.4f} mean similarity (stdev: {stdev(sims):.4f})")
            else:
                lines.append(f"    {condition:>20}: insufficient data")
        
        # Cross-condition similarity
        lines.append(f"\n  CROSS-CONDITION SIMILARITY (how different are conditions from each other):")
        for i in range(len(CONDITIONS)):
            for j in range(i + 1, len(CONDITIONS)):
                c1, c2 = CONDITIONS[i], CONDITIONS[j]
                codes1 = [r['main'].get('raw_code', '') for r in all_data[model][c1] if r['main'].get('exists') and r['main'].get('syntax_valid')]
                codes2 = [r['main'].get('raw_code', '') for r in all_data[model][c2] if r['main'].get('exists') and r['main'].get('syntax_valid')]
                
                if codes1 and codes2:
                    sims = []
                    for code1 in codes1:
                        for code2 in codes2:
                            sims.append(compute_similarity(code1, code2))
                    lines.append(f"    {c1} vs {c2}: {mean(sims):.4f} mean similarity")
        
        # Feature presence analysis
        lines.append(f"\n  FEATURE PRESENCE (per condition):")
        feature_keys = ['has_dataclass', 'has_enum', 'has_priority_queue', 'has_topological_sort',
                       'has_circular_detection', 'has_asyncio', 'has_exponential_backoff',
                       'has_semaphore', 'has_observer', 'has_metrics']
        feature_labels = ['Dataclass', 'Enum', 'Priority Queue', 'Topological Sort',
                         'Circular Detection', 'Asyncio', 'Exp. Backoff',
                         'Semaphore', 'Observer Pattern', 'Metrics']
        
        header = f"    {'Feature':<22}"
        for cond in CONDITIONS:
            header += f" | {cond:>14}"
        lines.append(header)
        lines.append("    " + "-" * 72)
        
        for fkey, flabel in zip(feature_keys, feature_labels):
            row = f"    {flabel:<22}"
            for cond in CONDITIONS:
                runs = all_data[model][cond]
                count = sum(1 for r in runs if r['main'].get(fkey, False))
                row += f" | {count}/{len(runs):>11}"
            lines.append(row)
    
    # ==========================================
    # KEY FINDINGS
    # ==========================================
    lines.append(f"\n\n{'='*80}")
    lines.append("  KEY FINDINGS & ANALYSIS")
    lines.append(f"{'='*80}\n")
    
    for model in MODELS:
        lines.append(f"\n--- {model.upper()} ---")
        
        complete_runs = all_data[model]['complete']
        interrupted_runs = all_data[model]['interrupted']
        fragment_runs = all_data[model]['fragment_continue']
        
        # Compare feature scores
        c_features = [r['main']['feature_score'] for r in complete_runs if r['main'].get('syntax_valid')]
        i_features = [r['main']['feature_score'] for r in interrupted_runs if r['main'].get('syntax_valid')]
        f_features = [r['main']['feature_score'] for r in fragment_runs if r['main'].get('syntax_valid')]
        
        if c_features and i_features:
            c_mean = mean(c_features)
            i_mean = mean(i_features)
            diff = i_mean - c_mean
            lines.append(f"\n  Feature completeness (complete vs interrupted): {c_mean:.1f} vs {i_mean:.1f} ({diff:+.1f})")
            if abs(diff) < 0.5:
                lines.append("    -> No significant difference in feature completeness")
            elif diff > 0:
                lines.append("    -> INTERRUPTED produces MORE complete code (re-generation effect)")
            else:
                lines.append("    -> INTERRUPTED produces LESS complete code")
        
        if c_features and f_features:
            c_mean = mean(c_features)
            f_mean = mean(f_features)
            diff = f_mean - c_mean
            lines.append(f"\n  Feature completeness (complete vs fragment): {c_mean:.1f} vs {f_mean:.1f} ({diff:+.1f})")
            if abs(diff) < 0.5:
                lines.append("    -> No significant difference")
            elif diff > 0:
                lines.append("    -> FRAGMENT+CONTINUE produces MORE complete code")
            else:
                lines.append("    -> FRAGMENT+CONTINUE produces LESS complete code")
        
        # Compare test counts
        c_tests = [r['test']['test_count'] for r in complete_runs if r['test'].get('exists')]
        i_tests = [r['test']['test_count'] for r in interrupted_runs if r['test'].get('exists')]
        f_tests = [r['test']['test_count'] for r in fragment_runs if r['test'].get('exists')]
        
        if c_tests and i_tests:
            lines.append(f"\n  Test count (complete vs interrupted): {mean(c_tests):.1f} vs {mean(i_tests):.1f}")
        if c_tests and f_tests:
            lines.append(f"  Test count (complete vs fragment): {mean(c_tests):.1f} vs {mean(f_tests):.1f}")
        
        # Code size comparison
        c_lines = [r['main']['total_lines'] for r in complete_runs if r['main'].get('exists')]
        i_lines = [r['main']['total_lines'] for r in interrupted_runs if r['main'].get('exists')]
        f_lines = [r['main']['total_lines'] for r in fragment_runs if r['main'].get('exists')]
        
        if c_lines and i_lines:
            c_mean = mean(c_lines)
            i_mean = mean(i_lines)
            pct = ((i_mean - c_mean) / c_mean) * 100
            lines.append(f"\n  Code size (complete vs interrupted): {c_mean:.0f} vs {i_mean:.0f} lines ({pct:+.1f}%)")
        if c_lines and f_lines:
            f_mean = mean(f_lines)
            pct = ((f_mean - c_mean) / c_mean) * 100
            lines.append(f"  Code size (complete vs fragment): {c_mean:.0f} vs {f_mean:.0f} lines ({pct:+.1f}%)")
    
    lines.append(f"\n\n{'='*80}")
    lines.append("  CONCLUSIONS")
    lines.append(f"{'='*80}\n")
    lines.append("  (See raw data in analysis/full_analysis.json for statistical details)")
    lines.append("")
    
    return '\n'.join(lines)


def main():
    print("Running analysis...")
    all_data = run_analysis()
    
    # Save raw data (without raw_code to keep file manageable)
    export_data = {}
    for model in all_data:
        export_data[model] = {}
        for condition in all_data[model]:
            export_data[model][condition] = []
            for run in all_data[model][condition]:
                run_export = {
                    'run': run['run'],
                    'main': {k: v for k, v in run['main'].items() if k != 'raw_code'},
                    'test': {k: v for k, v in run['test'].items() if k != 'raw_code'}
                }
                export_data[model][condition].append(run_export)
    
    with open(ANALYSIS_DIR / 'full_analysis.json', 'w') as f:
        json.dump(export_data, f, indent=2, default=str)
    
    report = generate_report(all_data)
    
    with open(ANALYSIS_DIR / 'report.txt', 'w') as f:
        f.write(report)
    
    print(report)


if __name__ == '__main__':
    main()
